/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iu;

import ConexionBBDD.ControllerBBDD;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author ThePandogs
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    ControllerBBDD controllerBBDD = new ControllerBBDD(this);

    public Interfaz() {
        initComponents();
        cargarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="GETTERS_SETTERS">  
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        background = new javax.swing.JPanel();
        usuariosJPanel = new javax.swing.JPanel();
        usuariosLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        botonesUsuarios = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 620));
        setName("APP_Hosteleria"); // NOI18N

        background.setBackground(new java.awt.Color(204, 204, 255));
        background.setMinimumSize(new java.awt.Dimension(600, 600));
        background.setPreferredSize(new java.awt.Dimension(600, 600));
        background.setLayout(new java.awt.GridBagLayout());

        usuariosJPanel.setBackground(new java.awt.Color(204, 204, 255));
        usuariosJPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        usuariosJPanel.setPreferredSize(new java.awt.Dimension(600, 600));
        usuariosJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuariosLbl.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        usuariosLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuariosLbl.setText("Usuarios");
        usuariosLbl.setMinimumSize(new java.awt.Dimension(0, 0));
        usuariosJPanel.add(usuariosLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 600, -1));

        botonesUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        botonesUsuarios.setPreferredSize(new java.awt.Dimension(500, 500));
        botonesUsuarios.setLayout(new java.awt.GridLayout(50, 50));
        jScrollPane1.setViewportView(botonesUsuarios);

        usuariosJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 530, 480));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 600;
        gridBagConstraints.ipady = 600;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        background.add(usuariosJPanel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel botonesUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel usuariosJPanel;
    private javax.swing.JLabel usuariosLbl;
    // End of variables declaration//GEN-END:variables

    private void cargarUsuarios() {
        int count = 0;
        ResultSet consulta = controllerBBDD.cargarUsuarios();
        try {
            while (consulta.next()) {
                for (int i = 0; i < 15; i++) {
                    if (count % 5 == 0) {
                        botonesUsuarios.setPreferredSize(new Dimension(botonesUsuarios.getX(), botonesUsuarios.getY() + 50));
                    }
                    JButton nuevoBoton = new javax.swing.JButton(consulta.getString(1));

                    nuevoBoton.setPreferredSize(new Dimension(botonesUsuarios.getWidth() / 5, botonesUsuarios.getHeight() / 5));
                    // nuevoBoton.setPreferredSize(new Dimension(botonesUsuarios.getWidth() / 5, botonesUsuarios.getHeight() / 5));
                    botonesUsuarios.add(nuevoBoton);
                    count++;
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
